version: 1.0.{build}
image: Visual Studio 2022

configuration: Release

init:
  - git config --global core.autocrlf false

before_build:
  - dotnet restore src/TypeGen/TypeGen.Cli
  - dotnet restore src/TypeGen/TypeGen.Core
  - dotnet restore src/TypeGen/TypeGen.Cli.Test
  - dotnet restore src/TypeGen/TypeGen.Core.Test
  - dotnet restore src/TypeGen/TypeGen.IntegrationTest
  - dotnet restore src/TypeGen/TypeGen.TestWebApp

build:
  project: src/TypeGen/TypeGen.sln
  
after_test:
  - ps: ./publish.ps1 -nobuild
  
artifacts:
  - path: '*.nupkg'
    name: NuGet packages
  
deploy:
  provider: NuGet
  api_key:
    secure: EuSmStKVNp99uph6Pdk2MWwEuo2wRJCW5yDnv0uEvJDOn/adbFNFGwlvjVWXHFLi
  skip_symbols: true
  on:
    branch: master
    APPVEYOR_REPO_TAG: true