version: 1.0.{build}
image: Visual Studio 2019

platform: Any CPU
configuration: Release

init:
- git config --global core.autocrlf false

before_build:
  - dotnet restore src/TypeGen/TypeGen.AcceptanceTest
  - dotnet restore src/TypeGen/TypeGen.Cli
  - dotnet restore src/TypeGen/TypeGen.Core
  - dotnet restore src/TypeGen/TypeGen.Cli.Test
  - dotnet restore src/TypeGen/TypeGen.Core.Test
  - dotnet restore src/TypeGen/TypeGen.TestWebApp

build:
  project: src/TypeGen/TypeGen.sln